- name: Build with Gradle
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: composeApp/build/outputs/apk/debug/*.apk
